# Generated by Django 4.0.5 on 2022-06-11 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webdev', '0003_ticket_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('ticket_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In_progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='author_assigned',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='author_completed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='author_filed',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
