# Generated by Django 4.0.5 on 2022-06-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0006_profile_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_name',
            new_name='domain',
        ),
    ]
