# Generated by Django 4.0.5 on 2022-06-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0007_rename_company_name_profile_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='domain',
            new_name='company_name',
        ),
    ]
